apiVersion: apps/v1
kind: Deployment
metadata:
  name: zechcodes-static-app
  labels:
    app: zechcodes-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zechcodes-static
  template:
    metadata:
      labels:
        app: zechcodes-static
    spec:
      containers:
        - image: registry.digitalocean.com/zechcodes/zechcodes-static-server:20210708
          name: zechcodes-static
          envFrom:
          - secretRef:
              name: zechcodes-secret
          - configMapRef:
              name: zechcodes-static
          ports:
            - containerPort: 8001
              name: static-server
